server:
  port: 8081


mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kf_bvd?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
  redis:
    host: localhost
    port: 6379
    timeout: 5000
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml



